<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <OutputPath>dist</OutputPath>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Authors>RichardLH</Authors>
        <Version>1.0.0.30</Version>
        <AssemblyVersion>1.0.0.30</AssemblyVersion>
        <FileVersion>1.0.0.30</FileVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
</Project>
